### ISSUE TITLE
Doppelte MAC-Adressen

### ISSUE THREAD

**Issue by FRNK-BK** [freifunkMUC/ffmap-backend#1]
Ich weiss nicht, ob dieses Repo das richtige ist, aber dennoch:
Wenn ich mir den Link 
http://map.freifunk-muenchen.de/node.html?id=12:01:ee:cd:96:26_1
anschaue, frage ich mich, woher das "_1" kommt.
Es gibt auch ohne suffix, der wird als unbekannt angezeigt.
Der "12:01:ee:cd:96:26_1" allerdings zeigt die Alfreddaten (?) des tatsächlichen Knotens, welcher in der LISTE und im GRAPH allerdings nur mit der MAC "12:01:ee:cd:96:26" (ohne Suffix) angezeigt wird. In der MAP werden Alfreddaten angezeigt.
Woher kommt die doppelte MAC (_1)? Wie kriegt man die da raus?

**Comment by dl1com** [comment]
Die MAC Adressen "..._1", "..._2", etc stellen die Clients dar. Ueber Alfred werden die tatsaechlichen MAC Adressen der Clients verteilt, die an den Knoten haengen. Aus (wsl. Privacy) Gruenden werden diese Adressen zur Darstellung in der Karte durch im ffmap-backend die MAC Adresse des Freifunk-Knotens plus Suffix mit aufsteigender Nummer ersetzt.
_Koennte_ man ausschalten, aber dann stehen halt die echten MAC-Adressen der Geraete der Benutzer da, keine Ahnung ob man das will/braucht.

**Comment by FRNK-BK** [comment]
Das hört sich ganz ok an. Das sollte man nicht ausschalten.
Leider klärt das nicht, warum beim angesprochenen Knoten die Alfred-Information immer nur beim "hinteren" Suffix angezeigt wird:
http://map.freifunk-muenchen.de/node.html?id=12:01:ee:cd:96:26_2
(Z. Zt. Nummer _2, zwei verbundene Clients)
http://map.freifunk-muenchen.de/node.html?id=12:01:ee:cd:96:26
bleibt ohne Information.
In der LISTE wird der Knoten dann eben auch nur als MAC-Adresse angezeigt, nicht mit Knotenname.
Wie lässt sich das erklären? Irgendwo ist da für mich ein Bug.

**Comment by FRNK-BK** [comment]
Allerdings wird im Widerspruch dazu, bei Nodes welche mit Name und mehreren verbundenen Clients in der LISTE stehen, unter http://map.freifunk-muenchen.de/node.html?id=<mac-adresse>_suffix
nichts angezeigt.

**Comment by dl1com** [comment]
Richtig, dass ein Knoten nur mit seiner 12:.. Adresse angezeigt wird (und dadurch auch keine Statistiken erscheinen etc.) ist ein Bug:
https://github.com/freifunkMUC/freifunkmuc.github.io/issues/69
@messimuc hat da kuerzlich auf der Mailingliste auch was dazu (+workaround) geschrieben, werde das in den o.g. issue reinpasten.

**Comment by FRNK-BK** [comment]
Aha, danke!

**Comment by dl1com** [comment]
siehe #2
