### ISSUE TITLE
Kontaktdaten anzeigen

### ISSUE THREAD

**Issue by hmuehlhans** [freifunkMUC/ffmap-backend#3]
Kontaktdaten aus nodes.json in der map anzeigen.

**Comment by dl1com** [comment]
done in 5176257133196e400a8c25ace49f704f501a03fe, still to be merged to the bat15 branch

**Comment by dl1com** [comment]
Merged from master to bat15: 71b8c99df4f0360d0de1cd4fa53a4daf0fcf5d64
(contained also the fix for strange displaying of some macs, good!)
